/**
 * SCILL API
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AuthApi", () => {
  let instance: api.AuthApi
  beforeEach(function() {
    instance = new api.AuthApi(config)
  });

  test("generateAccessToken", () => {
    const body: api.ForeignUserIdentifier = undefined
    return expect(instance.generateAccessToken(body, {})).resolves.toBe(null)
  })
})

describe("BattlePassesApi", () => {
  let instance: api.BattlePassesApi
  beforeEach(function() {
    instance = new api.BattlePassesApi(config)
  });

  test("claimBattlePassLevelReward", () => {
    const body: api.BattlePassLevelId = undefined
    const appId: string = "appId_example"
    const bpid: string = "bpid_example"
    return expect(instance.claimBattlePassLevelReward(body, appId, bpid, {})).resolves.toBe(null)
  })
  test("getBattlePass", () => {
    const appId: string = "appId_example"
    const bpid: string = "bpid_example"
    return expect(instance.getBattlePass(appId, bpid, {})).resolves.toBe(null)
  })
  test("getBattlePasses", () => {
    const appId: string = "appId_example"
    return expect(instance.getBattlePasses(appId, {})).resolves.toBe(null)
  })
  test("unlockBattlePassLevel", () => {
    const body: api.BattlePassLevelId = undefined
    const appId: string = "appId_example"
    const bpid: string = "bpid_example"
    return expect(instance.unlockBattlePassLevel(body, appId, bpid, {})).resolves.toBe(null)
  })
})

describe("ChallengesApi", () => {
  let instance: api.ChallengesApi
  beforeEach(function() {
    instance = new api.ChallengesApi(config)
  });

  test("activatePersonalChallenge", () => {
    const appId: string = "appId_example"
    const cid: string = "cid_example"
    return expect(instance.activatePersonalChallenge(appId, cid, {})).resolves.toBe(null)
  })
  test("cancelPersonalChallenge", () => {
    const appId: string = "appId_example"
    const cid: string = "cid_example"
    return expect(instance.cancelPersonalChallenge(appId, cid, {})).resolves.toBe(null)
  })
  test("claimPersonalChallengeReward", () => {
    const appId: string = "appId_example"
    const cid: string = "cid_example"
    return expect(instance.claimPersonalChallengeReward(appId, cid, {})).resolves.toBe(null)
  })
  test("generateWebsocketAccessToken", () => {
    return expect(instance.generateWebsocketAccessToken({})).resolves.toBe(null)
  })
  test("getActivePersonalChallenges", () => {
    const appId: string = "appId_example"
    return expect(instance.getActivePersonalChallenges(appId, {})).resolves.toBe(null)
  })
  test("getPersonalChallenges", () => {
    const appId: string = "appId_example"
    return expect(instance.getPersonalChallenges(appId, {})).resolves.toBe(null)
  })
  test("unlockPersonalChallenge", () => {
    const appId: string = "appId_example"
    const cid: string = "cid_example"
    return expect(instance.unlockPersonalChallenge(appId, cid, {})).resolves.toBe(null)
  })
})

describe("EventsApi", () => {
  let instance: api.EventsApi
  beforeEach(function() {
    instance = new api.EventsApi(config)
  });

  test("sendEvent", () => {
    const body: api.EventPayload = undefined
    return expect(instance.sendEvent(body, {})).resolves.toBe(null)
  })
})

