apiVersion: v1
kind: Service
metadata:
  name: scill-gaas-example-1
  labels:
    app: scill-gaas-example-1
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: scill-gaas-example-1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scill-gaas-example-1
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: example.release.app.scillplay.com
    http:
      paths:
      - backend:
          serviceName: scill-gaas-example-1
          servicePort: 80
  tls:
  - secretName: example-release-app-scillplay-com-tls-cert
    hosts:
    - example.release.app.scillplay.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scill-gaas-example-1
spec:
  selector:
    matchLabels:
      app: scill-gaas-example-1
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: scill-gaas-example-1
    spec:
      containers:
        - image: eu.gcr.io/cloud-apps-198613/scill-gaas-example-js:latest
          imagePullPolicy: Always
          env:
            - name: BUILD
              value: '{CI_COMMIT_REF_NAME}'
          name: scill-gaas-example-1
          resources:
            requests:
              cpu: 0.1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/local/secrets"
              name: certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: example-release-app-scillplay-com-tls-cert
